import jsonlines
import argparse

def get_query_posi_doc_ans(args):
    with jsonlines.open(args.query_path, 'r') as reader1, \
        jsonlines.open(args.doc_path, 'r') as reader2, \
        jsonlines.open(args.answer_path, 'r') as reader3, \
        jsonlines.open(args.outfile, 'w') as writer:
        for indata1, indata2, indata3 in zip(reader1, reader2, reader3):
            query = indata1['query']
            posi = indata1['positive']
            docs = indata2['passages']
            ans = indata3['answer']
            outdata = {"query": query,"positive": posi, "passages": docs, "answer": ans}
            writer.write(outdata)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--query_path", type=str, 
                        default=None,
                        help="The path of queries and positive documents"
                        )
    parser.add_argument("--doc_path", type=str, 
                        default=None,
                        help="The path of documents file generated by llm."
                        )
    parser.add_argument("--answer_path", type=str, 
                        default=None,
                        help="The path of answer file generated by llm."
                        )
    
    parser.add_argument("--outfile", type=str,
                        help="The path of (query, positive, docs, ans) file."
                        )

    args = parser.parse_args()
    get_query_posi_doc_ans(args)

if __name__ == "__main__":
    main()
